#!/usr/bin/python
# Programmer : zhuxp
# Date: 
# Last-modified: 02 Oct 2012 10:42:53
import types
from xplib.Annotation import OddsRatioSNP

def OddsRatioSNPIterator(handle,**kwargs):
    '''
    Wrapper in TableIO.parse(file or filename,"oddsratiosnp")
    Usage:
        for i in TableIO.parse(file or filename,"oddsratiosnp"):
            print i
    yield the xplib.Annotation.OddsRatioSNP class object.

    the oddsratiosnp file should be generated by program xbams2APS.py.
    Please See xplib.Annotation.OddsRatioSNP document for detail description.
    '''
    if type(handle)==type("s"):
        try:
            handle=open(handle,"r")
        except:
            raise ValueError("Can't open file %s"%handle)
    for line in handle:
        line=line.strip()
        if len(line)==0: continue
        if line[0]=="#": continue
        x=line.split("\t")
        x=OddsRatioSNP(x)
        yield x
    return
    
