# Programmer : zhuxp
# Date: 
# Last-modified: 03 Oct 2012 17:06:31
import types
from xplib.Annotation import OddsRatioSNP
import SimpleIO
def OddsRatioSNPIterator(handle,**kwargs):
    '''
    Wrapper in TableIO.parse(file or filename,"oddsratiosnp")
    Usage:
        for i in TableIO.parse(file or filename,"oddsratiosnp"):
            print i
    yield the xplib.Annotation.OddsRatioSNP class object.

    the oddsratiosnp file should be generated by program xbams2APS.py.
    Please See xplib.Annotation.OddsRatioSNP document for detail description.
    '''
    for x in SimpleIO.SimpleIterator(handle,**kwargs):
        x=OddsRatioSNP(x)
        yield x
    return
    
